import { Direction } from '@/common';

const GAME_FIELD_SIZE = 10;

const GAME_SPEED_MULTIPLIER = 0.7;

const GOLD_APPLE_PROBABILITY = 10;

const DIAMOND_APPLE_PROBABILITY = 15;

const GOLD_APPLE_POINT = 5;

const DIAMOND_APPLE_POINT = 10;

const REGULAR_APPLE_POINT = 1;

const INITIAL_SNAKE_CORD = [
  { x: 0, y: 0 },
  { x: 1, y: 0 },
  { x: 2, y: 0 },
  { x: 3, y: 0 },
];

const INITIAL_SNAKE_MOVE_DIRECTION = Direction.RIGHT;

const INITIAL_SPEED = 500;

export {
  GAME_FIELD_SIZE,
  GAME_SPEED_MULTIPLIER,
  GOLD_APPLE_PROBABILITY,
  DIAMOND_APPLE_PROBABILITY,
  DIAMOND_APPLE_POINT,
  GOLD_APPLE_POINT,
  REGULAR_APPLE_POINT,
  INITIAL_SNAKE_CORD,
  INITIAL_SNAKE_MOVE_DIRECTION,
  INITIAL_SPEED,
};
